version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # painel do Traefik (opcional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" # ajuste conforme seu domínio
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=24"
    expose:
      - "24"

  backend:
    build:
      context: ./backend       # a pasta que você vai criar
      dockerfile: Dockerfile   # crie um Dockerfile simples lá dentro
    env_file:
      - ./.env
    # ou, alternativamente:
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    labels:
      - "traefik.enable=true"
      # aqui você pode usar sub-domínio ou path; ex. api.localhost
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=1010"
    expose:
      - "1010"
    depends_on:
      - traefik                # opcional, só pra deixar claro a ordem

  # volumes, networks, etc, se quiser trazer Postgres, Redis etc.

